{% set name = "mockupdb" %}
{% set version = "1.8.0" %}
{% set sha256 = "8832627ee23c6df620ed86a4ccc5ca71f0375e704b1686851950946cd22b1f8c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - mockupdb
  requires:
    - pymongo >=3

about:
  home: https://github.com/ajdavis/mongo-mockup-db
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: MongoDB Wire Protocol server library
  doc_url: http://mockupdb.readthedocs.org/
  dev_url: https://github.com/ajdavis/mongo-mockup-db

extra:
  recipe-maintainers:
    - hodgsonw
